title: Akshaj Pages 
description: "Class of 2025"
owner_name: Akshaj Gurugubelli
github_username: Akshaj-G
github_repo: "Akshaj_2025" 
baseurl: "/Akshaj_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/akshaj-gurugubelli-11a66129b/" }

# remote_theme: pages-themes/midnight@v0.2.0
#  remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/49ers.md
  - navigation/journey.md
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/games.md
  - navigation/CSPlesson.md
  - README4YML.md
